import sys
import time
from app.services.tts_service import TTSService

start = time.time()
print("Initializing TTSService...")
tts = TTSService()
print(f"Loaded in {time.time() - start:.2f} seconds.")

start_infer = time.time()
print("Running synthesize()...")
try:
    audio_bytes = tts.synthesize("???", "santali")
    print(f"Synthesize completed in {time.time() - start_infer:.2f} seconds.")
    print(f"Generated bytes: {len(audio_bytes)}")
    
    with open("production_test.wav", "wb") as f:
        f.write(audio_bytes)
        
    import wave
    with wave.open("production_test.wav", "rb") as w:
        print(f"Channels: {w.getnchannels()}")
        print(f"Sample Width: {w.getsampwidth()}")
        print(f"Framerate: {w.getframerate()}")
        print(f"Frames: {w.getnframes()}")
        
    import numpy as np
    import soundfile as sf
    data, sr = sf.read("production_test.wav")
    print(f"Max amp: {np.max(np.abs(data))}")
    if np.max(np.abs(data)) > 0:
        print("SUCCESS: Non-zero audio")
    else:
        print("FAILED: Audio is silence")
except Exception as e:
    print(f"FAILED: {e}")
