from enum import Enum
from pydantic import BaseModel, Field, validator
from typing import Optional

class VerificationStatus(str, Enum):
    VERIFIED_HUMAN = "VERIFIED_HUMAN"
    REVIEWED_HUMAN = "REVIEWED_HUMAN"
    MACHINE_GENERATED = "MACHINE_GENERATED"
    BACK_TRANSLATED = "BACK_TRANSLATED"
    UNVERIFIED = "UNVERIFIED"
    REJECTED = "REJECTED"

class ScriptVariant(str, Enum):
    DEVANAGARI = "Devanagari"
    OL_CHIKI = "Ol_Chiki"
    ROMAN = "Roman"
    UNKNOWN = "Unknown"

class DomainCategory(str, Enum):
    FLN = "FLN"
    NUMERACY = "NUMERACY"
    LITERACY = "LITERACY"
    CLASSROOM = "CLASSROOM"
    ASSESSMENT = "ASSESSMENT"
    ACTIVITY = "ACTIVITY"
    GENERAL = "GENERAL"
    CONVERSATION = "CONVERSATION"

class NMTRecord(BaseModel):
    id: str = Field(..., description="Unique identifier for the parallel pair")
    source_language: str = Field("hi", description="Source ISO code")
    target_language: str = Field("sat", description="Target ISO code")
    source_script: ScriptVariant = Field(default=ScriptVariant.DEVANAGARI)
    target_script: ScriptVariant = Field(default=ScriptVariant.OL_CHIKI)
    source_text: str = Field(..., min_length=1, description="Hindi source text")
    target_text: str = Field(..., min_length=1, description="Santhali target text")
    domain: DomainCategory = Field(default=DomainCategory.GENERAL)
    verification_status: VerificationStatus = Field(default=VerificationStatus.UNVERIFIED)
    source: str = Field(..., description="Provenance (e.g. EnSanCorp, AdiBhashaa, or internal annotator ID)")
    translator_id: Optional[str] = None
    quality_score: Optional[float] = Field(None, ge=0.0, le=1.0)
    split: Optional[str] = Field(None, description="train, validation, or test")
    synthetic: bool = Field(False, description="Must be true if generated by a machine model")

    @validator('synthetic')
    def validate_synthetic_status(cls, v, values):
        if v and values.get('verification_status') in [VerificationStatus.VERIFIED_HUMAN, VerificationStatus.REVIEWED_HUMAN]:
            raise ValueError("Synthetic data cannot be marked as VERIFIED_HUMAN or REVIEWED_HUMAN")
        return v

    @validator('split')
    def validate_test_split(cls, v, values):
        if v == "test":
            if values.get('synthetic'):
                raise ValueError("Synthetic data cannot be in the GOLD test set")
            if values.get('verification_status') not in [VerificationStatus.VERIFIED_HUMAN, VerificationStatus.REVIEWED_HUMAN]:
                raise ValueError("Only verified human translations can be in the GOLD test set")
        return v
